name: Generate JoyAndCo Product Feeds

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate_feeds:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium
    
    - name: Run crawler
      run: python crawler.py
    
    - name: Commit and push feed files
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        
        # Create feeds directory if it doesn't exist
        mkdir -p feeds
        
        # Check if there are any changes to commit
        if [ -n "$(git status --porcelain feeds/)" ]; then
          git add feeds/
          git commit -m "Update product feeds $(date +'%Y-%m-%d')"
          git push
        else
          echo "No changes to commit"
        fi
