name: Generate JoyAndCo Product Feeds

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight daily
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # This gives the workflow permission to write to the repository

jobs:
  generate_feeds:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install all dependencies except playwright
        grep -v "playwright" requirements.txt > requirements_no_pw.txt
        pip install -r requirements_no_pw.txt
        # Install lxml, asyncio, and other needed packages explicitly
        pip install lxml asyncio python-dateutil pytz
    
    - name: Setup Playwright
      uses: microsoft/playwright-github-action@v1
    
    - name: Install Playwright Python
      run: |
        pip install playwright
        playwright install chromium
    
    - name: Run crawler
      run: |
        # Create feeds directory if it doesn't exist
        mkdir -p feeds
        mkdir -p debug
        # Run crawler with detailed output
        python crawler.py
        # Show debug directory contents for logging
        ls -la debug/ || true
        ls -la feeds/ || true
    
    - name: Commit and push feed files
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        
        # Add the feeds directory
        git add feeds/
        
        # Check if there are any changes to commit
        if [ -n "$(git status --porcelain feeds/)" ]; then
          git commit -m "Update product feeds $(date +'%Y-%m-%d')"
          git push
        else
          echo "No changes to commit in feeds directory"
        fi
