name: Generate JoyAndCo Product Feeds

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight daily
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # This gives the workflow permission to write to the repository

jobs:
  generate_feeds:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        # Install required system dependencies for Playwright
        sudo apt-get install -y libasound2t64 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libdbus-1-3 \
          libxkbcommon0 libatspi2.0-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libpango-1.0-0 \
          libcairo2 libnss3 libxss1 libnspr4
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Playwright browsers
      run: |
        # Use the skip browser download flag and install manually
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 pip install playwright
        # Install Chromium browser with system dependencies
        playwright install-deps chromium
        playwright install chromium
    
    - name: Run crawler
      run: |
        # Create feeds directory if it doesn't exist
        mkdir -p feeds
        mkdir -p debug
        # Run crawler with detailed output
        python crawler.py
        # Show debug directory contents for logging
        ls -la debug/ || true
    
    - name: Commit and push feed files
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        
        # Add the feeds directory
        git add feeds/
        
        # Check if there are any changes to commit
        if [ -n "$(git status --porcelain feeds/)" ]; then
          git commit -m "Update product feeds $(date +'%Y-%m-%d')"
          git push
        else
          echo "No changes to commit in feeds directory"
        fi
